configs: Enable sysreset for our sama5 based boards
Fixes build failures like these (buildman):

           arm:  +   muxgate
    +arch/arm/lib/reset.o: In function `do_reset':
    +arch/arm/lib/reset.c:42: undefined reference to `reset_cpu'
    +make[1]: *** [Makefile:1813: u-boot] Fehler 1
    +make: *** [Makefile:177: sub-make] Error 2
           arm:  +   vera2
    +arch/arm/lib/reset.o: In function `do_reset':
    +arch/arm/lib/reset.c:42: undefined reference to `reset_cpu'
    +make[1]: *** [Makefile:1813: u-boot] Fehler 1
    +make: *** [Makefile:177: sub-make] Error 2

Fixes: 71d4393f84 ("sysreset: Add Atmel/Microchip sysreset driver")
Fixes: 085f7378e3 ("configs: at91: Enable SYSRESET for Atmel/Microchip's platforms")
For: v2022.07