configs: ncl: Move autoboot settings to defconfig
Fixes the following compiler warning:

  CC      common/autoboot.o
In file included from include/config.h:7:0,
                 from include/common.h:18,
                 from common/autoboot.c:8:
common/autoboot.c: In function 'abortboot_keyed':
include/configs/at91sam9g20ncl.h:76:33: warning: too many arguments for format [-Wformat-extra-args]
 #define CONFIG_AUTOBOOT_PROMPT  "Hit keys 'is' to stop autoboot (%d seconds).\n", bootdelay
                                 ^
common/autoboot.c:199:9: note: in expansion of macro 'CONFIG_AUTOBOOT_PROMPT'
  printf(CONFIG_AUTOBOOT_PROMPT, bootdelay);
         ^

For: v2015.07
See: d126e016493d ("autoboot.c: Move config options to Kconfig")